### ISSUE TITLE
Can't import project

### ISSUE THREAD

**Issue by evis** [ValdemarGr/mezel#13]
I've tried to import project with VSCode + metals + mezel, but it didn't work out.

Logs:
metals.log: https://gist.github.com/evis/9855e2f16709da5387e00e0b593b3789
metals-to-mezel: https://gist.github.com/evis/83514fb80bc6557f612fa3226da95d61
mezel-to-metals: https://gist.github.com/evis/528de70661b68c82faae47273f24313b

It's just getting restarted in loop.

**Comment by ValdemarGr** [comment]
Thanks for the report!

Metals will time the BSP server out if it doesn't respond fast enough.
[From your logs](https://gist.github.com/evis/9855e2f16709da5387e00e0b593b3789#file-gistfile1-txt-L35-L36) it looks like another Bazel process is running, do you run multiple instances of `mezel` at once? Bazel is mutually exclusive for the same `output_base` when running actions, so they'll block eachother.

Can you try manually running the command:
```sh
'bazel' '--output_base=/private/var/tmp/_bazel_vere10/mezel-8371961849d659ce3605b8a0d6ee6fd8' 'info' '--noshow_loading_progress' '--noshow_progress'
```

Your naming of the repository `contrib_mezel` might also cause issues further down the line since `mezel` [expects the aspect to be at a specific label](https://github.com/ValdemarGr/mezel/blob/85f8f90ee288729df418dad5aed5e33168e9521b/README.md?plain=1#L103).

**Comment by evis** [comment]
Fixed contrib_mezel and checked that no Bazel process is running here, but still couldn't import

close this issue for now, maybe will try later
